In [1]:
from keras.models import load_model


Using TensorFlow backend.


In [2]:
model = load_model('VGG_face_recog.h5')

In [5]:
import os
import cv2
import numpy as np
from os import listdir
from os.path import isfile, join

faces_dict = {"[0]": "jai", 
                      "[1]": "rudra"}
                    

faces_dict_n = {"jai":"jai","rudra":"rudra" }


def draw_test(name, pred, im):
    faces = faces_dict[str(pred)]
    BLACK = [0,0,0]
    expanded_image = cv2.copyMakeBorder(im, 80, 0, 0, 100 ,cv2.BORDER_CONSTANT,value=BLACK)
    cv2.putText(expanded_image, faces, (20, 60) , cv2.FONT_HERSHEY_SIMPLEX,1, (0,0,255), 2)
    cv2.imshow(name, expanded_image)

def getRandomImage(path):
    """function loads a random images from a random folder in our test path """
    folders = list(filter(lambda x: os.path.isdir(os.path.join(path, x)), os.listdir(path)))
    random_directory = np.random.randint(0,len(folders))
    path_class = folders[random_directory]
    print("Class - " + faces_dict_n[str(path_class)])
    file_path = path + path_class
    file_names = [f for f in listdir(file_path) if isfile(join(file_path, f))]
    random_file_index = np.random.randint(0,len(file_names))
    image_name = file_names[random_file_index]
    return cv2.imread(file_path+"/"+image_name)    

for i in range(0,10):
    input_im = getRandomImage("faces/validation/")
    input_original = input_im.copy()
    input_original = cv2.resize(input_original, None, fx=0.5, fy=0.5, interpolation = cv2.INTER_LINEAR)
    
    input_im = cv2.resize(input_im, (224, 224), interpolation = cv2.INTER_LINEAR)
    input_im = input_im / 255.
    input_im = input_im.reshape(1,224,224,3) 
    
    # Get Prediction
    res = np.argmax(model.predict(input_im, 1, verbose = 0), axis=1)
    
    # Show image with predicted class
    draw_test("Prediction", res, input_original) 
    cv2.waitKey(0)

cv2.destroyAllWindows()

Class - jai
Class - rudra
Class - jai
Class - rudra
Class - rudra
Class - jai
Class - jai
Class - rudra
Class - rudra
Class - jai


In [4]:

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('VGG_face_recog.h5')
# Loading the cascades
face_cascade = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
  
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
          #Resizing into 224X224 because we trained the model with this image size.
        
        im = Image.fromarray(face, 'RGB')
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 224x224x3 into 1x224x224x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.8):
            name= "User Found ,Confidence Level:" + str(int(pred[0][0]) * 100)
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break
video_capture.release()
cv2.destroyAllWindows()

<>:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-4-a69f6c840964>:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.000000e+00 4.374452e-36]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 1.4228004e-22]]
[[9.9999976e-01 1.9719931e-07]]
[[1.000000e+00 9.385309e-33]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 1.7217423e-19]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.000000e+00 8.547273e-27]]
[[1. 0.]]
[[1.2120619e-09 1.0000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 1.0304152e-09]]
[[1.000000e+00 2.002897e-24]]
[[3.7895388e-04 9.9962103e-01]]
[[1.000000e+00 4.293849e-23]]
[[1.0000000e+00 1.9902892e-19]]
[[8.9799733e-13 1.0000000e+00]]
[[2.2731632e-12 1.0000000e+00]]
[[9.9999440e-01 5.5752703e-06]]
[[0.93169904 0.06830096]]
[[9.999920e-01 7.975197e-06]]
[[1. 0.]]
[[1.0000000e+00 5.0844615e-32]]
[[1.0000000e+00 4.8462595e-11]]
[[1. 0.]]
[[1. 0.]]
[[2.6641694e-12 1.0000000e+00]]
[[1.0000000e+00 2.3414164e-18]]
[[1.000000e+00 1.979428e-30]]
[[1.000000e+00 4.833387e-35]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 6.6581926e-36]]
[[1.0000000e+00 2.7731628e-16]]
[[2.0200734e